### ISSUE TITLE
500 Server Error ( Error: Must provide a proper URL as target )

### ISSUE THREAD

**Issue by yelnyafacee** [maximilianschmitt/next-auth#2]
Hi, I tried this example and I got:

```
500 Internal Server Error

Error: Must provide a proper URL as target
    at ProxyServer.<anonymous> (C:\xampp\htdocs\lounge-react\node_modules\http-proxy\lib\http-proxy\index.js:69:35)
    at C:\xampp\htdocs\lounge-react\.next\server\pages\api\proxy\[...path].js:165:11
    at new Promise (<anonymous>)
    at module.exports../pages/api/proxy/[...path].js.__webpack_exports__.default (C:\xampp\htdocs\lounge-react\.next\server\pages\api\proxy\[...path].js:132:10)
    at apiResolver (C:\xampp\htdocs\lounge-react\node_modules\next\dist\next-server\server\api-utils.js:8:7)
    at DevServer.handleApiRequest (C:\xampp\htdocs\lounge-react\node_modules\next\dist\next-server\server\next-server.js:64:492)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.fn (C:\xampp\htdocs\lounge-react\node_modules\next\dist\next-server\server\next-server.js:56:492)
    at async Router.execute (C:\xampp\htdocs\lounge-react\node_modules\next\dist\next-server\server\router.js:23:67)
    at async DevServer.run (C:\xampp\htdocs\lounge-react\node_modules\next\dist\next-server\server\next-server.js:66:1042)
    at async DevServer.handleRequest (C:\xampp\htdocs\lounge-react\node_modules\next\dist\next-server\server\next-server.js:34:504)
    
```
for the path `http://localhost:3000/api/proxy/login` and `http://localhost:3000/api/proxy/user`, any idea what I did wrong?

**Comment by maximilianschmitt** [comment]
Hi @yelnyaface! Did you make any modifications to the code in this repo? From your stack trace it looks like you're running on Windows, which I didn't test, so potentially there are some issues there... 🤔

**Comment by maximilianschmitt** [comment]
The issue was fixed: https://github.com/maximilianschmitt/next-auth/pull/3
